// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nn2
List nn2(NumericMatrix data, NumericMatrix query, const int k, const double eps = 0.0);
RcppExport SEXP RANN2_nn2(SEXP dataSEXP, SEXP querySEXP, SEXP kSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type query(querySEXP );
        Rcpp::traits::input_parameter< const int >::type k(kSEXP );
        Rcpp::traits::input_parameter< const double >::type eps(epsSEXP );
        List __result = nn2(data, query, k, eps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
