# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nn2 <- function(data, query, k, eps = 0.0) {
    .Call('RANN2_nn2', PACKAGE = 'RANN2', data, query, k, eps)
}

